name: Run Selenium Tests with Allure Reporting

on:
  push:
    branches:
      - main
      - allure

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out this repo
        uses: actions/checkout@v2

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Run Maven Tests
      - name: Run Maven Tests
        run: mvn clean test --batch-mode --fail-at-end

      # Generate Allure Report
      - name: Generate Allure Report
        run: mvn allure:report --batch-mode

      # Publish Allure Report as GitHub Pages
      - name: Publish Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: target/site/allure-maven-plugin
          github_token: ${{ secrets.GITHUB_TOKEN }}
