name: Run Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out this repo
        uses: actions/checkout@v2

      # Set up Python for WebDriver management
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Remove any existing Chromium/Chrome installations
      - name: Remove Chrome
        run: sudo apt purge -y google-chrome-stable || true
      - name: Remove default Chromium
        run: sudo apt purge -y chromium-browser || true

      # Install a new version of Chromium
      - name: Install a new Chromium
        run: sudo apt install -y chromium-browser

      # Install necessary Python packages for WebDriver management
      - name: Install Python packages
        run: pip install requests beautifulsoup4 pandas webdriver-manager selenium

      - name: Sudo Apt Get Update
        run: sudo apt-get update

      - name: Install Linux Libs
        run: sudo apt-get install -y libnss3 libgdk-pixbuf2.0-0 libxss1 libappindicator3-1 libasound2


      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Set up Maven
      - name: Set up Maven
        uses: s4u/maven-settings-action@v2

      # Install dependencies and run Maven tests
      - name: Run Maven Tests
        run: mvn test
