name: Run Selenium Tests

on:
  push:
    branches:
      - main
      - surefire

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out this repo
        uses: actions/checkout@v2

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Set up Maven
      - name: Set up Maven
        uses: s4u/maven-settings-action@v2

      # Install dependencies and run Maven tests
      - name: Run Maven Tests
        run: mvn test --batch-mode --fail-at-end
      
      - name: LS
        run: |
          echo "Displaying Surefire reports:"
          ls -R /home/runner/work/selenium-java
  
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: '/home/runner/work/selenium-java/selenium-java/target/surefire-reports/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Automation Tests Report

      # Publish Surefire HTML Report
      - name: Publish Extent Reports
        if: success() || failure()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: '/home/runner/work/selenium-java/selenium-java/target/'  # Ensure this directory contains index.html
          github_token: ${{ secrets.GITHUB_TOKEN }}